services:
  portal:
    image: yasminalencar/viaserra-portal:1.0-26174744
    ports:
      - "8044:80"
    restart: unless-stopped

  manutencao:
    build: ./manutencao
    ports:
      - "7044:80"
    restart: unless-stopped